### ISSUE TITLE
Unable to SSH to any instance

### ISSUE THREAD

**Issue by gshutler** [oracle/terraform-kubernetes-installer#173] opened 2018-03-22 16:17 UTC
### Terraform Version

```
Terraform v0.11.5
+ provider.null v1.0.0
+ provider.oci v2.1.1
+ provider.random v1.1.0
+ provider.template v1.0.0
+ provider.tls v1.1.0
```

### OCI Provider Version

```
$ ~/.terraform.d/plugins/terraform-provider-oci_v2.1.1
2018/03/22 16:06:42 [INFO] terraform-provider-oci 2.1.1
```

### Terraform Installer for Kubernetes Version

https://github.com/oracle/terraform-kubernetes-installer/commit/11a75b298d0a462ab5cb261f2c3262ab7fd3a7ee (master)

### Input Variables

Defaults other than authentication and:

```
region = "uk-london-1"
etcdShape = "VM.Standard2.1"
k8sMasterShape = "VM.Standard2.1"
k8sWorkerShape = "VM.Standard2.1"
natInstanceShape = "VM.Standard2.1"

etcd_ssh_ingress = "0.0.0.0/0"
master_ssh_ingress = "0.0.0.0/0"
worker_ssh_ingress = "0.0.0.0/0"
master_https_ingress = "0.0.0.0/0"
worker_nodeport_ingress = "0.0.0.0/0"
public_subnet_http_ingress = "0.0.0.0/0"
public_subnet_https_ingress = "0.0.0.0/0"
```

### Description of issue:

Unable to ssh to instances after `terraform apply` has executed successfully.

```
$ scripts/cluster-check.sh
[cluster-check.sh] Running some basic checks on Kubernetes cluster....
[cluster-check.sh]   Checking SSH connectivity to each node (from this host)...
[cluster-check.sh]   [FAILED] Could not ssh to master <IPADDRESS>
[cluster-check.sh]   Only IPs in 0.0.0.0/0 are allowed to SSH to this node
[cluster-check.sh]   If it is not correct, set master_ssh_ingress in terraform.tfvars to a CIDR that includes the IP              of this host and run terraform plan and apply
```

Everything looks ok in logs, etc. Verified the SSH key is ok (also tried from scratch with a different SSH key in case that was to blame). I get the authenticity prompt when using SSH so it seems the instances are reachable.

If I create a console connection to the instance through the dashboard I'm prompted to provide a username and password which suggests the ssh key hasn't been added correctly but I can't spot the problem.

---

I've also tried using the latest release rather than master but that failed during `terraform plan` in a different way:

```
Error: Error running plan: 1 error(s) occurred:

* module.instances-etcd-ad1.oci_core_instance.TFInstanceEtcd: 1 error(s) occurred:

* module.instances-etcd-ad1.oci_core_instance.TFInstanceEtcd: At column 47, line 1: list "data.oci_core_images.ImageOCID.images" does not have any elements so cannot determine type. in:

${lookup(data.oci_core_images.ImageOCID.images[0], "id")}
```

**Comment by gshutler** [comment] 2018-03-22 17:13
Found that the Kubernetes cluster seemed to be up and running correctly but that there was a failing pod. Managed to get some logs from that:

```
Logs from
oci-volume-provisioner
in
oci-volume-provisioner-d565fc7f5-ls678
F0322 17:08:53.752715       1 provisioner.go:89] Unable to create volume provisioner client: can not create client, bad region configuration: region named: uk-london-1, not valid
```

Could this be the root cause?

**Comment by garthy** [comment] 2018-03-22 20:04
Ok that bug in volume provisioning. Shouldn't cause SSH to break.

I'll test out London tomorrow and take a look.

**Comment by gshutler** [comment] 2018-03-22 21:12
Great, thanks.

**Comment by gshutler** [comment] 2018-03-23 10:51
I thought I'd try and eliminate `uk-london-1` as a variable this morning and so ran against `eu-frankfurt-1`. `scripts/cluster-check.sh` eventually passed with basically the same config other than the region change and switching to `VM1.x` shapes.

I've now tried it against `uk-london-1` again and `scripts/cluster-check.sh` is passing and I can `ssh` on to the instances. I'm at a bit of a loss as to what has changed as I'm definitely using the exact same config as yesterday as it's all in git.

**Comment by garthy** [comment] 2018-03-23 11:49
Well interestingly enough I've just reproduced it. I'm going to access the
machines via the console and see what is going on.

**Comment by garthy** [comment] 2018-03-23 13:48
OK I hadn't regenerated my ssh key! This works for me now. I'm closing if it works for you? We'll update the components for the volume provisioner to support London

**Closed** 2018-03-23 13:52 UTC
